// Contenido de PRODUCCIÓN para temario-maestro.txt — Bloque 2, Unidad 7
// (lecciones 26-36: "Qué es cripto y por qué importa" — reestructurada v2,
// 11 lecciones en vez de 8, agrega el bloque de dinero digital/CBDC).
// Mismo formato exacto que TEORIA / PREGUNTAS en curso-inversiones.html,
// con un campo extra `contenedor` por lección: indica qué estilo visual de
// pregunta (de los 10 del constructor en React) le corresponde por defecto,
// tomado de las etiquetas "Contenedor:" del temario v2.
// Ids con prefijo tm_ + lección relativa a la unidad (tm_u7l1..tm_u7l11).

const TEORIA_TM_B2_U7 = {
  tm_u7l1:{titulo:"Tu dinero ya es 90% digital aunque no lo veas",
    contenedor:"clasico",
    texto:["Tu sueldo no llega en billetes: llega como un número que cambia en la base de datos de tu banco. Ya confías en dinero digital todos los días, solo que no lo llamas así.",
           "Se cae la app del banco un rato y, aunque tengas saldo de sobra, no puedes pagar nada hasta que vuelva — el dinero seguía ahí, pero dependías 100% de que el sistema del banco funcionara."],
    dato:"El billete físico es la excepción, no la regla: la mayoría de tu dinero ya vive como un número en un sistema que no controlas tú.",
    ejemplo:"Pagas la renta por transferencia, cobras tu sueldo por depósito, pagas el súper con tarjeta — en un día normal, puedes no tocar un solo billete físico y aun así mover miles de pesos. Ese número que sube y baja en tu app ya es, técnicamente, dinero digital.",
    error:"Pensar que 'cripto' es la primera vez que tu dinero deja de ser físico — llevas años usando dinero digital cada vez que usas tu tarjeta o tu app de banco; lo que cambia con cripto no es 'ser digital', es quién controla ese número.",
    contexto:"Esta distinción (dinero digital bancario vs. cripto vs. CBDC) es la base de todo lo que viene en esta unidad — no es un tecnicismo, es la diferencia entre quién tiene el control real sobre tu dinero en cada caso."},

  tm_u7l2:{titulo:"Los 4 tipos de dinero digital",
    contenedor:"pareja",
    texto:["Bancario (el número en tu app de BBVA/Santander), stablecoin (USDT/USDC, cripto que vale ~$1 dólar), CBDC (peso digital emitido directo por el banco central) y Bitcoin (descentralizado, sin dueño ni emisor).",
           "Los 4 'son un número en una pantalla', pero quién los controla y qué tan programables son cambia completamente entre uno y otro."],
    dato:"Un vale de despensa es dinero 'programable' — solo sirve en ciertas tiendas, para ciertas cosas. Los 4 tipos de dinero digital se diferencian, sobre todo, en cuánto de ese control tiene alguien más sobre tu dinero.",
    ejemplo:"Tienes $1,000 repartidos en los 4 tipos: en tu banco, tu institución puede congelarlos si hay una orden judicial; en USDC, la empresa emisora puede, en teoría, bloquear direcciones específicas; en una CBDC, el banco central podría programar en qué se gasta; en Bitcoin, nadie individual tiene ese poder sobre tu saldo.",
    error:"Tratar los 4 tipos como si fueran intercambiables solo porque todos 'son un número en una pantalla' — la tecnología detrás se parece, pero quién tiene la llave para congelar, rastrear o programar ese número es radicalmente distinto en cada uno.",
    contexto:"Esta clasificación no es exclusiva de este curso — es la forma estándar en que economistas y analistas de política monetaria distinguen los tipos de dinero digital que existen hoy en el mundo."},

  tm_u7l3:{titulo:"CBDC: cuando el gobierno hace su propia cripto",
    contenedor:"caso",
    texto:["CBDC = moneda digital de banco central. Nigeria lanzó el eNaira en 2021; China opera el e-CNY (yuan digital) a gran escala; Banxico en México ha hecho pruebas piloto sin fecha pública confirmada de lanzamiento.",
           "Ventaja real: pagos instantáneos, sin intermediarios. Riesgo real: puede ser programable, rastreable y hasta caducar."],
    dato:"El e-CNY chino está construido para poder programarse — técnicamente se le puede poner fecha de caducidad a un saldo, o limitarlo a ciertos tipos de compra, algo que un billete físico nunca podría hacer.",
    ejemplo:"China ha probado repartir e-CNY como estímulo con fecha de caducidad — si no lo gastas antes de cierta fecha, el saldo deja de ser válido. Es una función técnicamente posible en una CBDC que sería imposible de replicar con billetes físicos en tu bolsillo.",
    error:"Asumir que 'CBDC' es automáticamente lo mismo que 'app de banco, pero del gobierno' — la diferencia real no es quién la emite, es que una CBDC puede construirse con capacidades de programabilidad y rastreo que un depósito bancario normal no tiene por diseño.",
    contexto:"No todas las CBDC del mundo son idénticas: el eNaira de Nigeria, el e-CNY chino y las pruebas piloto de Banxico en México son proyectos distintos con distintos niveles de adopción y capacidades — 'CBDC' es una categoría, no un solo diseño único."},

  tm_u7l4:{titulo:"El riesgo de que todo sea digital y rastreable",
    contenedor:"duelo",
    altoRiesgo:true,
    texto:["Congelamiento de cuentas, vigilancia total de en qué gastas, exclusión si 'no calificas', y programabilidad (que alguien más decida qué SÍ puedes comprar con tu dinero). Sin efectivo de respaldo, no tienes plan B.",
           "En 2022, Canadá invocó la Ley de Emergencias y congeló alrededor de 210 cuentas bancarias (~$7.8 millones de dólares) ligadas a las protestas de transportistas, sin necesitar orden judicial previa. Ese mismo año, Nigeria limitó los retiros de efectivo en cajeros a apenas ~$225 dólares por semana (y luego bajó el límite de retiro en tiendas a ~$45 dólares al día) específicamente para forzar el uso del eNaira."],
    dato:"Ninguno de los dos casos necesitó que tu dinero 'desapareciera' — bastó con que alguien más decidiera que no podías usarlo.",
    ejemplo:"En el caso de Canadá 2022, las cuentas congeladas no perdieron su saldo — simplemente dejaron de poder usarlo. Para esas personas, en la práctica, ese dinero se volvió inútil durante el congelamiento, aunque el número siguiera existiendo en la pantalla.",
    error:"Pensar que esto 'nunca podría pasarte a ti' porque no participas en protestas o actividades políticas — el punto no es si estás de acuerdo con la causa de cada caso, es que el mecanismo técnico (congelar sin orden judicial previa) existe y ya se usó, sin importar la situación específica.",
    contexto:"Estos son dos casos documentados y verificables (Canadá 2022, Nigeria 2022) — no son hipótesis o escenarios especulativos, son eventos reales que ya ocurrieron y son de conocimiento público."},

  tm_u7l5:{titulo:"Cómo protegerte: efectivo, diversificación y autocustodia",
    contenedor:"orden",
    texto:["Por eso importa tener opciones: una parte en efectivo, una parte en el banco, y una parte en autocustodia (una wallet que solo tú controlas).",
           "No es paranoia, es no depender de un solo sistema que alguien más puede apagar, congelar o programar."],
    dato:"Tu 'colchón digital' es tener una wallet con tu frase semilla guardada — el equivalente cripto de no meter TODOS tus ahorros a un solo banco.",
    ejemplo:"Alguien reparte su dinero en tres 'canastas': algo de efectivo en casa para emergencias inmediatas, la mayoría en su banco para el día a día, y una porción en una wallet propia que solo él controla — si un sistema falla o se congela, los otros dos siguen disponibles.",
    error:"Confundir 'diversificar entre sistemas de dinero' con desconfianza extrema o paranoia — es el mismo principio de diversificación que ya viste con inversiones en el Bloque 1, aplicado a dónde vive tu dinero, no solo a en qué está invertido.",
    contexto:"Esta lógica no es exclusiva de cripto ni nueva — es el mismo principio detrás del consejo financiero clásico de no tener todos tus ahorros en un solo banco o un solo instrumento, aplicado ahora también al tipo de sistema de dinero."},

  tm_u7l6:{titulo:"Wallets: tu wallet vs. tu cuenta en un exchange",
    contenedor:"pareja",
    texto:["Una wallet es tuya de verdad, como el dinero bajo el colchón. Una cuenta en un exchange es como tener el dinero en la caja fuerte de otra persona.",
           "Si el exchange cierra o te bloquea la cuenta, tu dinero se queda atorado ahí. Si tu wallet es tuya, nadie más tiene la llave."],
    dato:"'Wallet' no guarda tu cripto adentro como una alcancía — guarda las llaves que prueban que ese dinero es tuyo.",
    ejemplo:"Tu cripto en realidad vive registrada en la blockchain, no 'dentro' de tu wallet — la wallet solo guarda la llave privada que demuestra que esos registros son tuyos y te permite moverlos. Si pierdes esa llave, no es que 'se borre' tu cripto, es que pierdes la forma de probar y usar que es tuya.",
    error:"Pensar que basta con 'tener una wallet' para estar protegido, sin entender que la seguridad real depende de cómo guardas tu frase semilla — una wallet mal respaldada (foto en el celular, nube sin cifrar) puede ser tan vulnerable como dejar la contraseña de tu banco en un papel pegado en el monitor.",
    contexto:"La diferencia entre wallet propia y cuenta en exchange no es solo técnica, es de responsabilidad: en un exchange, si algo sale mal, hay una empresa a la que reclamar (con sus propios límites); en tu propia wallet, la responsabilidad completa es tuya, sin nadie más a quien acudir."},

  tm_u7l7:{titulo:"Not your keys, not your coins",
    contenedor:"duelo",
    texto:["'No custodio' significa que tus fondos nunca pasan por las manos de la plataforma — están en TU cuenta todo el tiempo, no en la de ellos. Así opera Dasus.",
           "Es la diferencia entre dejar tu coche en un valet parking (ellos tienen las llaves mientras tanto) y manejarlo tú mismo hasta el cajón."],
    dato:"Si no controlas la llave privada, en la práctica no controlas el dinero, aunque la app diga que es tuyo.",
    ejemplo:"Varios exchanges centralizados a lo largo de la historia de cripto han pausado retiros durante periodos de estrés del mercado — mientras tu saldo seguía apareciendo en pantalla, no podías moverlo. Con fondos en tu propia wallet, esa situación específica no puede pasar, porque nadie más tiene el poder de pausar tus retiros.",
    error:"Asumir que 'no custodio' es una característica exclusiva o inventada por Dasus — es un principio general de cómo puede diseñarse una plataforma cripto, y aplica igual a cualquier interfaz construida sobre un protocolo donde tú mantienes el control de tus llaves.",
    contexto:"La frase 'not your keys, not your coins' es una expresión muy repetida dentro de la comunidad cripto desde hace años — resume en pocas palabras la lección central de esta unidad: el control real depende de quién tiene la llave, no de qué dice la interfaz."},

  tm_u7l8:{titulo:"Conectar con solo un correo",
    contenedor:"clasico",
    texto:["Puedes empezar a operar sin instalar nada raro: una 'llave de sesión' se crea para ti y firma operaciones simples, sin darle a nadie el control total de tu dinero.",
           "Es como darle a un valet una llave que solo mueve el coche del estacionamiento a la salida — no puede sacarlo a la calle, venderlo, ni llevárselo."],
    dato:"Esta llave de sesión ('agent wallet') la vas a ver con más detalle técnico en la Unidad 13.",
    ejemplo:"Conectas con tu correo y en segundos ya puedes ver mercados y precios en tiempo real, sin haber instalado ninguna extensión ni memorizado una frase semilla todavía — el paso de custodia completa (wallet propia) llega después, cuando decides operar con fondos reales.",
    error:"Confundir 'poder empezar con solo un correo' con 'ya no importa entender wallets y custodia' — es una forma de reducir la fricción para explorar la plataforma, pero en cuanto metes fondos reales, entender qué puede y no puede hacer esa llave de sesión sigue siendo esencial.",
    contexto:"Esta llave de sesión no reemplaza a una wallet propia — es un mecanismo adicional que facilita operar sin confirmar cada acción manualmente, dentro de límites estrictos que el protocolo define (lo verás con más detalle técnico en la Unidad 13)."},

  tm_u7l9:{titulo:"INTERACCIÓN — Abre tu wallet descentralizada de verdad",
    contenedor:"interaccion",
    texto:["Ejercicio funcional, no teoría: instala una wallet real (MetaMask, Rabby u OneKey), genera tu frase semilla, guárdala físicamente —nunca en foto ni en la nube— y confirma que la entendiste antes de seguir.",
           "Es como si te dieran una caja fuerte y TÚ eligieras la combinación: si la olvidas o la pierdes, ni el fabricante de la caja puede abrirla por ti."],
    dato:"Una frase semilla típica son 12 o 24 palabras en orden específico. Cualquiera que las tenga controla tu wallet, sin excepción.",
    ejemplo:"Alguien genera su wallet por primera vez, anota las 12 palabras a mano en un papel (nunca en foto ni en la nube), y las guarda en un lugar físico seguro distinto de donde guarda su dispositivo — si pierde el celular, todavía puede recuperar el acceso con esas palabras en otro dispositivo.",
    error:"Guardar la frase semilla como captura de pantalla en el celular o en una nota de la nube 'porque es más práctico' — cualquier dispositivo o cuenta conectada a internet es un punto de posible robo; el papel físico guardado en un lugar seguro sigue siendo el estándar más seguro.",
    contexto:"Este es un ejercicio funcional, no solo teoría — la meta es que hayas pasado por el proceso real al menos una vez (generar, anotar, guardar) antes de mover cualquier fondo real a esa wallet."},

  tm_u7l10:{titulo:"INTERACCIÓN — Abre una cuenta en un exchange centralizado (CEX)",
    contenedor:"interaccion",
    texto:["Ejercicio funcional: regístrate en un exchange centralizado (correo + verificación KYC) y observa dónde queda tu dinero en ese flujo: en SU custodia, no en la tuya.",
           "Es como abrir una cuenta en un banco — te piden identificación, y el banco (no tú) es quien físicamente resguarda tu dinero mientras está ahí."],
    dato:"KYC son las siglas de 'Know Your Customer' — la verificación de identidad que piden los exchanges centralizados, algo que una wallet no-custodia nunca te pide.",
    ejemplo:"Al registrarte en un exchange centralizado, subes tu identificación oficial y quizás una foto de tu rostro antes de poder depositar — es un proceso similar a abrir una cuenta bancaria, porque técnicamente estás confiando tu dinero a la custodia de esa empresa, igual que confías tu dinero a un banco.",
    error:"Pensar que un exchange centralizado (CEX) es automáticamente 'menos seguro' o 'peor' que una wallet propia — tienen ventajas reales (facilidad de uso, soporte al cliente, a veces protección regulatoria) a cambio de ceder el control directo de tus llaves; no es una elección de bueno vs. malo, es un trade-off distinto.",
    contexto:"Este es otro ejercicio funcional — la meta es que veas con tus propios ojos, en un flujo real, exactamente en qué momento tu dinero deja de estar en tu wallet y pasa a la custodia de la empresa, algo que en abstracto es más difícil de notar."},

  tm_u7l11:{titulo:"Centralizada vs. descentralizada vs. CBDC: la tabla que debes memorizar",
    contenedor:"pareja",
    texto:["3 columnas: CEX (Binance-style), Wallet propia (la tuya), CBDC (peso digital de gobierno). Quién puede congelar tu saldo, quién puede ver cada movimiento, y quién puede programar cómo lo gastas — en las 3, la respuesta cambia.",
           "Usar un CEX es como rentar un departamento amueblado; tener tu wallet es ser dueño de tu casa; una CBDC es como vivir en una casa donde el dueño del terreno puede cambiar las reglas cuando quiera."],
    dato:"No es 'cuál es mejor' — es cuál para qué: CEX para operar seguido y fácil, wallet propia para lo que no quieres arriesgar en manos de un tercero, y CBDC es la que menos control te da a ti.",
    ejemplo:"Alguien podría usar un CEX para operar montos chicos de forma ágil, mover la mayor parte de sus ahorros cripto a su propia wallet para custodia de largo plazo, y seguir usando su cuenta bancaria normal para el día a día — las 3 opciones conviviendo, cada una para lo que mejor resuelve.",
    error:"Buscar 'la mejor opción única' entre las 3, como si una tuviera que ganarle a las otras dos en todo — cada una resuelve un problema distinto (comodidad, control, integración con el sistema tradicional), y la mayoría de la gente termina usando una combinación, no una sola.",
    contexto:"Esta tabla comparativa resume toda la Unidad 7: quién controla tu dinero, quién puede verlo, y quién puede limitarlo cambia según el tipo de sistema que elijas — es la base para entender por qué el resto del curso, desde la Unidad 8, se centra en cómo opera Dasus específicamente sobre el modelo no-custodia."},
};

// IMPORTANTE (regla #5 actualizada, ver reglas.txt): cada lección usa UN
// SOLO tipo de pregunta — el de su `contenedor` en TEORIA — no se mezclan
// estilos dentro del mismo nodo. Para contenedores de "bloque único" (pareja,
// orden, clasificar) eso puede significar 1 sola pregunta rica en vez de 3
// copias forzadas del mismo bloque.
const PREGUNTAS_TM_B2_U7 = {
  tm_u7l1:[ // contenedor: clasico → mcq x3
    {tipo:"mcq",q:"¿Cómo llega la mayoría de tu sueldo hoy en día?",
     opciones:["Siempre en efectivo","Como un número que cambia en la base de datos de tu banco","Solo en cheque físico","No aplica, todo es en efectivo en México"],
     correcta:1,expl:"Tu sueldo ya es, en su mayoría, un número digital en el sistema del banco — no billetes esperándote en una bóveda."},
    {tipo:"mcq",q:"Se cae la app de tu banco un rato y no puedes pagar nada, aunque tienes saldo de sobra. ¿Qué significa esto?",
     opciones:["Perdiste tu dinero","El dinero sigue ahí, pero dependes de que el sistema digital funcione","El banco te lo robó","Nunca deberías tener dinero en un banco"],
     correcta:1,expl:"El dinero no desaparece, pero dependes 100% de que el sistema funcione para poder usarlo."},
    {tipo:"mcq",q:"¿Qué te dice ese episodio (app caída, saldo intacto pero inusable) sobre tu dinero 'físico' en el banco?",
     opciones:["Que en realidad no tienes ese dinero","Que ya vives con dinero mayormente digital, aunque no lo notes en el día a día","Que el banco cometió un fraude","Que deberías sacar todo en efectivo"],
     correcta:1,expl:"Ya dependes de un sistema digital todos los días — el episodio solo hace visible esa dependencia."},
  ],
  tm_u7l2:[ // contenedor: pareja → 1 match rico (4 parejas), no se fuerzan 3 copias
    {tipo:"match",q:"Relaciona cada tipo de dinero digital con su definición correcta:",
     pares:[
       {izq:"Bancario",der:"Número en tu app de BBVA/Santander, controlado por el banco"},
       {izq:"Stablecoin",der:"Cripto que busca valer siempre ~$1 dólar (ej. USDT/USDC)"},
       {izq:"CBDC",der:"Peso digital emitido directo por el banco central"},
       {izq:"Bitcoin",der:"Descentralizado, sin dueño ni emisor único"},
     ],
     // fallback mcq (solo para el motor viejo de curso-inversiones.html, que no tiene UI de "match"):
     opciones:["Bancario→banco, Stablecoin→~$1 dólar, CBDC→banco central, Bitcoin→descentralizado","Bancario y Bitcoin son controlados por el mismo banco central","CBDC es descentralizada, igual que Bitcoin","Los 4 tipos son exactamente lo mismo, solo cambia el nombre"],correcta:0,
     expl:"Los 4 son 'un número en una pantalla', pero cambia radicalmente quién los controla y qué tan programables son."},
  ],
  tm_u7l3:[ // contenedor: caso → case x3
    {tipo:"case",q:"Un amigo te dice que una CBDC 'es exactamente lo mismo que tener tu dinero en el banco de siempre'. ¿Qué es en realidad una CBDC?",
     opciones:["Una cripto descentralizada sin dueño","Una moneda digital emitida y controlada directo por el banco central de un país","Un tipo de stablecoin privada","Un exchange centralizado"],
     correcta:1,expl:"CBDC = Central Bank Digital Currency: dinero digital emitido y controlado directamente por el banco central."},
    {tipo:"case",q:"El e-CNY (yuan digital de China) puede programarse para tener fecha de caducidad o limitarse a ciertas compras. ¿Qué ventaja real tiene también una CBDC bien implementada?",
     opciones:["Ninguna, solo tiene riesgos","Pagos instantáneos, sin intermediarios","Anonimato total como el efectivo","Que nunca puede fallar"],
     correcta:1,expl:"La ventaja real es velocidad y eliminar intermediarios en el pago — el riesgo es la programabilidad y trazabilidad, no que sea 'inútil'."},
    {tipo:"case",q:"Alguien afirma que 'Banxico ya lanzó su peso digital al público, con fecha confirmada'. ¿Qué le respondes con lo que sabes?",
     opciones:["Es correcto, ya está disponible para todos","Falso — Banxico ha hecho pruebas piloto, sin fecha pública confirmada de lanzamiento","Solo está disponible en el norte del país","Se lanzó hace más de 5 años"],
     correcta:1,expl:"Banxico ha hecho pruebas piloto (vía un proyecto del BIS), pero no hay fecha pública confirmada de lanzamiento al público general."},
  ],
  tm_u7l4:[ // contenedor: duelo → duelo x3 (altoRiesgo)
    {tipo:"duelo",q:"¿Cuál de estos dos casos reales muestra el riesgo de que TODO tu dinero sea digital y rastreable?",
     opciones:["En 2022, Canadá congeló ~210 cuentas bancarias (~$7.8M USD) ligadas a protestas, sin orden judicial previa","En 2022, un banco mexicano subió sus comisiones por transferencia SPEI"],
     correcta:0,expl:"El caso de Canadá 2022 (Ley de Emergencias) es el ejemplo real de congelamiento masivo de cuentas sin ese trámite previo — una comisión más alta no es lo mismo que perder acceso a tu dinero."},
    {tipo:"duelo",q:"¿Por qué Nigeria limitó los retiros de efectivo en cajeros a ~$225 USD/semana en 2022?",
     opciones:["Para forzar la adopción del eNaira (su CBDC)","Para combatir la inflación"],
     correcta:0,expl:"Fue una medida explícita del banco central para empujar a la gente a usar el eNaira en lugar de efectivo."},
    {tipo:"duelo",q:"¿Cuál es el verdadero problema de fondo detrás de los casos de Canadá y Nigeria?",
     opciones:["Que sin efectivo de respaldo, no tienes 'plan B' si alguien más bloquea tu dinero digital","Que las apps bancarias eran lentas ese año"],
     correcta:0,expl:"En ambos casos no fue necesario que el dinero 'desapareciera' — bastó con que un tercero decidiera que no podías usarlo."},
  ],
  tm_u7l5:[ // contenedor: orden → 1 order (3 pasos), no se fuerzan 3 copias
    {tipo:"order",q:"Ordena esta forma de protegerte, de lo más líquido/inmediato a lo más autónomo:",
     pasos:["Efectivo a la mano","Dinero en el banco","Autocustodia (wallet propia)"],
     // fallback mcq (motor viejo):
     opciones:["Efectivo → Banco → Autocustodia","Autocustodia → Banco → Efectivo","Banco → Autocustodia → Efectivo","Autocustodia → Efectivo → Banco"],correcta:0,
     expl:"Efectivo = inmediato pero limitado; banco = cómodo pero depende de terceros; autocustodia = control total, pero también toda la responsabilidad."},
  ],
  tm_u7l6:[ // contenedor: pareja → 1 match rico
    {tipo:"match",q:"Relaciona cada situación con la custodia a la que corresponde:",
     pares:[
       {izq:"Tu wallet propia",der:"Tú tienes la llave — nadie más puede moverla sin tu permiso"},
       {izq:"Tu cuenta en un exchange",der:"La plataforma tiene la llave — tu dinero depende de que te lo devuelvan"},
       {izq:"Exchange que cierra o te bloquea",der:"Tu dinero puede quedar atorado ahí"},
       {izq:"Wallet que es tuya de verdad",der:"Nadie más tiene la llave, pase lo que pase con terceros"},
     ],
     opciones:["Wallet=tu llave, Exchange=llave de la plataforma","Ambas dan exactamente el mismo control","El exchange siempre es más seguro que tu wallet","No hay ninguna diferencia real"],correcta:0,
     expl:"Tu wallet es tuya de verdad; en un exchange, tu dinero depende de que la plataforma te lo devuelva."},
  ],
  tm_u7l7:[ // contenedor: duelo → duelo x3
    {tipo:"duelo",q:"¿Cuál de estas dos definiciones describe 'no custodio' (como opera Dasus)?",
     opciones:["Tus fondos nunca pasan por las manos de la plataforma — quedan en tu cuenta todo el tiempo","La plataforma guarda tus fondos en su cuenta y te los presta cuando los pides"],
     correcta:0,expl:"Tus fondos están en TU cuenta todo el tiempo — la plataforma nunca los tiene en la suya."},
    {tipo:"duelo",q:"¿Cuál de estas dos opciones se parece más a 'no custodio'?",
     opciones:["Manejar tú mismo tu coche hasta el cajón","Dejar tu coche con un valet"],
     correcta:0,expl:"Manejarlo tú mismo: nadie más tiene las llaves en ningún momento — igual que una wallet no-custodia."},
    {tipo:"duelo",q:"¿Cómo termina correctamente el dicho 'Not your keys, ___'?",
     opciones:["not your coins","not your bank"],
     correcta:0,expl:"'Not your keys, not your coins': si no controlas la llave privada, en la práctica no controlas el dinero."},
  ],
  tm_u7l8:[ // contenedor: clasico → mcq x3
    {tipo:"mcq",q:"¿Qué puede hacer la 'llave de sesión' que se crea al conectar con solo un correo?",
     opciones:["Retirar tu dinero a cualquier dirección","Firmar operaciones simples como abrir o cerrar posiciones","Cambiar el dueño de la cuenta","Transferir fondos a otra cuenta"],
     correcta:1,expl:"Solo firma operaciones de trading — nunca retiros, transferencias, ni cambios de dueño."},
    {tipo:"mcq",q:"Conectar con solo un correo, ¿le da a la plataforma control total de tu dinero?",
     opciones:["Sí, control total","No — solo puede firmar operaciones simples, nunca retiros ni transferencias","Sí, pero solo los primeros 30 días","No, no puede hacer nada en absoluto"],
     correcta:1,expl:"Es como la llave del valet: mueve el coche dentro del estacionamiento, pero no puede sacarlo a la calle."},
    {tipo:"mcq",q:"Firmaste la autorización de tu llave de sesión en Dasus. Alguien te pide que se la compartas 'para ayudarte a operar mejor'. ¿Qué haces?",
     opciones:["Se la doy, si me ayuda no hay problema","No — nadie más debe usar mi llave de sesión, ni con buenas intenciones","Solo si me paga","Se la doy solo por WhatsApp"],
     correcta:1,expl:"La llave de sesión es tuya y solo tuya — igual que la frase semilla, nadie legítimo la necesita para 'ayudarte'."},
  ],
  tm_u7l9:[ // contenedor: interaccion → case x3 (ejercicio funcional, se evalúa por escenario)
    {tipo:"case",q:"Un compañero de curso te pregunta a quién le puede compartir su frase semilla, 'si de verdad confía en la persona'. ¿Qué le respondes?",
     opciones:["A nadie, nunca — ni a 'soporte técnico'","Solo a alguien de mucha confianza","A la plataforma, para que la respalde","Depende de cuánto confíe en esa persona"],
     correcta:0,expl:"Nadie legítimo te la va a pedir jamás. Cualquiera que la tenga controla tu wallet completa, sin excepción."},
    {tipo:"case",q:"Terminaste de generar tu frase semilla en tu wallet nueva. ¿Dónde la guardas?",
     opciones:["En una nota en tu celular","En una foto en la nube","Escrita a mano, en un lugar físico seguro","En un mensaje de WhatsApp a ti mismo"],
     correcta:2,expl:"Físico y offline. Foto, nube o mensaje la exponen a que alguien más la copie sin que te des cuenta."},
    {tipo:"case",q:"Perdiste tu frase semilla, pero recuerdas el correo y la contraseña de la wallet. Intentas 'recuperar el acceso' como en cualquier app. ¿Qué pasa?",
     opciones:["Te mandan un correo de reseteo, como cualquier cuenta","No hay recuperación posible — la frase semilla ES el acceso, sin ella no hay forma de entrar","Soporte técnico te la puede regenerar","Puedes acceder solo con la contraseña"],
     correcta:1,expl:"Una wallet no-custodia no tiene 'recuperar contraseña' — la frase semilla es el único acceso que existe."},
  ],
  tm_u7l10:[ // contenedor: interaccion → case x3
    {tipo:"case",q:"Al registrarte en un exchange centralizado (CEX), te piden subir una identificación oficial antes de dejarte operar. ¿Qué es esto y por qué lo piden?",
     opciones:["Un error del sistema","El proceso de KYC ('Know Your Customer') que exige la regulación a los exchanges centralizados","Un intento de vender tus datos","Algo que una wallet no-custodia también exige"],
     correcta:1,expl:"KYC es la verificación de identidad que la regulación exige a los exchanges centralizados — algo que una wallet propia nunca pide."},
    {tipo:"case",q:"Terminaste tu registro y verificación en un CEX. ¿Dónde queda guardado tu dinero mientras opera ahí?",
     opciones:["En tu propia wallet, nadie más la controla","En custodia de la plataforma, no en la tuya","No se guarda en ningún lado hasta que retiras","Se reparte automático entre varias wallets tuyas"],
     correcta:1,expl:"En un CEX el dinero queda en custodia de la plataforma, no en la tuya — la diferencia clave frente a una wallet no-custodia."},
    {tipo:"case",q:"El CEX donde te registraste anuncia 'pausa de retiros por mantenimiento' justo cuando querías sacar tu dinero. ¿Por qué puede pasar esto?",
     opciones:["Es imposible, nunca pasa","Porque tu dinero está en SU custodia, no en la tuya","Porque perdiste tu wallet","Porque no pagaste comisión"],
     correcta:1,expl:"En un exchange, tu dinero depende de que la plataforma te lo devuelva cuando lo pidas — ese es el riesgo de la custodia de terceros."},
  ],
  tm_u7l11:[ // contenedor: pareja → 1 match rico (3 columnas)
    {tipo:"match",q:"Relaciona cada opción de custodia con lo que más la define:",
     pares:[
       {izq:"CEX (exchange centralizado)",der:"Confías en la empresa; puede congelar o bloquear tu cuenta"},
       {izq:"Wallet propia",der:"Tú controlas todo; nadie más puede congelarla sin tu llave"},
       {izq:"CBDC",der:"El banco central puede, en teoría, programar y rastrear cómo la gastas"},
     ],
     opciones:["CEX=confías en la empresa, Wallet=controlas tú, CBDC=controla el emisor","Las 3 dan exactamente el mismo control","CBDC da más control a ti que una wallet propia","Ninguna de las 3 tiene control real sobre el dinero"],correcta:0,
     expl:"No es 'cuál es mejor' — es cuál para qué: CEX para operar fácil, wallet propia para lo que no arriesgas con terceros, CBDC es la que menos control te da a ti."},
  ],
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { TEORIA_TM_B2_U7, PREGUNTAS_TM_B2_U7 };
}
